site_name: å‡¯æ¥½æ–¯Kelesssã®è–æ•™å¤©å ‚
# å¯¼èˆªæ 
nav:
  - ğŸ é¦–é¡µ:
    - ğŸ é¦–é¡µ: index.md
    - â²ï¸æœ€è¿‘æ›´æ–°: changelog.md
    - ğŸ™‹æˆ‘è¦æŠ•ç¨¿ï¼: commit.md
  - ğŸ§ªåŒ–å­¦:
    - åŒ–å­¦-é¦–é¡µ: "chem/index.md"
    - ç‰©ç†åŒ–å­¦:
      - ç‰©ç†åŒ–å­¦IIç¬”è®°: "chem/physical/Physical Chemistry II.md"
    - ç«èµ›æ™¶ä½“è¿›é˜¶åè®²:
      - 0.å‰è¨€: "chem/crystaljs/perface.md"
      - 1.å®è§‚æ™¶ä½“ä¸å¯¹ç§°æ€§: "chem/crystaljs/lecture1.md"
      - 2.æ™¶ä½“çš„è¡¨å¾ã€Braggæ–¹ç¨‹ä¸ç³»ç»Ÿæ¶ˆå…‰: "chem/crystaljs/lecture2.md"
      - 3.å †ç§¯ã€å¤šé¢ä½“ä¸æ™¶ä½“æ„é€ : "chem/crystaljs/lecture3.md"
      - 4.æ™¶ä½“ä¸å…‰ç”µç£: "chem/crystaljs/lecture4.md"
      - 5.å•è´¨æ™¶ä½“: "chem/crystaljs/lecture5.md"
      - 6.å…«é¢ä½“é…ä½çš„æ™¶ä½“: "chem/crystaljs/lecture6.md"
      - 7.å››é¢ä½“é…ä½çš„æ™¶ä½“: "chem/crystaljs/lecture7.md"
      - 8.ä½“å¿ƒç«‹æ–¹: "chem/crystaljs/lecture8.md"
      - 9.åˆ†å­æ™¶ä½“åŠå…¶ä»–: "chem/crystaljs/lecture9.md"
      - 10.æ™¶ä½“ä¸­çš„æ•°å­¦æ¨å¯¼: "chem/crystaljs/lecture10.md"
  - ğŸ”¢æ•°ç†:
    - æ•°ç†-é¦–é¡µ: "maphy/index.md"
    - æ•°å­¦åŸºç¡€:
      - æ•°å­¦ç‰©ç†æ–¹æ³•: "maphy/math/Mathematic Method in Physics.md"
    - çƒ­å­¦ä¸çƒ­åŠ›å­¦:
      - ç»Ÿè®¡çƒ­åŠ›å­¦: "maphy/thermo_phys/Statistic_Thermodynamics.md"
  - ğŸ–¥ï¸è®¡ç®—æœº:
    - è®¡ç®—æœº-é¦–é¡µ: "cs/index.md"
  - â˜•æ‚è´§é“º:
    - æ‚è´§é“º-é¦–é¡µ: "lqbz/index.md"
    - è–æ•™ç›¸å…³:
      - å‡¯æ¥½æ–¯ç¤¾ä¼šå­¦æ•™æ: lqbz/holykelesss/social1.md
    - å¼±æ™ºé¢˜å¤§åˆé›†:
      - å¤±é‡çš„é­…åŠ›1: lqbz/sbprob/sz1.md
      - å¤±é‡çš„é­…åŠ›2: lqbz/sbprob/sz2.md
      - å¤±é‡çš„é­…åŠ›3: lqbz/sbprob/sz3.md
      - å¤±é‡çš„é­…åŠ›4: lqbz/sbprob/sz4.md
      - å¤±é‡çš„é­…åŠ›5: lqbz/sbprob/sz5.md
      - å¹¿ä¹‰çš„çƒ­é‡åˆ†æ: lqbz/sbprob/gyrz.md
      - â€œæ±‰ç¥æ¯â€å…ƒç´ æ¨æ–­å¤§èµ›: lqbz/sbprob/hsb.md
      - Î³Chem æ¨æ–­é¢˜é€‰: lqbz/sbprob/ystd.md
      - å¦‚é‡‘ Ruby Gold: lqbz/sbprob/rubygold.md
    - é”è¯„:
      - é”è¯„æ‰€æœ‰å°‘å¥³ä¹é˜Ÿç•ªå‰§: lqbz/rp/band.md

  - ğŸ“šèµ„æ–™:
    - èµ„æ–™-é¦–é¡µ: refs/index.md
    - åŒ–å­¦ç›¸å…³ä¹¦ç±: 
      - ç‰©ç†åŒ–å­¦: refs/cbook/phys.md
      - æ— æœºåŒ–å­¦-çƒ­é—¨ğŸ”¥: refs/cbook/inorg.md
      - æ— æœºåŒ–å­¦-æ‹“å±•ğŸ’¥: refs/cbook/inorg2.md
      - æœ‰æœºåŒ–å­¦-çƒ­é—¨ğŸ”¥: refs/cbook/org.md
      - æœ‰æœºåŒ–å­¦-æ‹“å±•ğŸ’¥: refs/cbook/org2.md
      - åˆ†æåŒ–å­¦: refs/cbook/anal.md
      - é«˜åˆ†å­ç‰©ç†å’ŒåŒ–å­¦: refs/cbook/polymer.md
      - ç†è®ºä¸è®¡ç®—åŒ–å­¦: refs/cbook/quant.md
      - å…¶ä»–ä¹¦ç±: refs/cbook/other.md
    - èµ„æºåˆ†äº«:
      - åŒ–å­¦ç›¸å…³: refs/software/chemsoft.md
      - æ•°å­¦ç›¸å…³: refs/software/mathsoft.md
    - åŒ–å­¦ç«èµ›é¢˜ç›®:
      - PKU&THUæ˜¥è”/é‡‘ç§‹è¥è¯•é¢˜: refs/jsexam/pkuthu.md
  - ğŸ““æ—¥è®°:
    - æ—¥è®°-é¦–é¡µ: blog/index.md

use_directory_urls: false

# materialä¸»é¢˜
theme:
  name: material
  custom_dir: overrides

  palette: 
    - scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  lang: zh
  favicon: libs/logos/favicon.png
  logo: libs/logos/favicon.png
  
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - search suggest
    - search highlight
    - search share
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - navigation.top

plugins:
  - search:
      lang: 
        - zh
        - en
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
  - meta
  - blog: 
      blog_toc: true
      archive_date_format: MMMM yyyy
  - changelog
  - heti:
      disable_serve: true
  - glightbox
  - statistics
  - minify:
      minify_html: true

hooks:
  - hooks/toc.py

#é¡µè„š
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/SUPERkelesss
      - icon: bilibili-fill
        link: https://space.bilibili.com/334614292
      - icon: QQgroup
        link: https://qm.qq.com/q/YXattqg3Kg
      - icon: rednote
        link: https://www.xiaohongshu.com/user/profile/659dd609000000002001ca3b
      - icon: zhihu
        link: https://www.zhihu.com/people/ke-le-kelesss
copyright: Copyright Â© 2025 by <a href="https://github.com/SUPERkelesss" target="_blank">Kelesss</a> is licensed under CC BY-SA 4.0
#é¡µçœ‰
repo_url: https://github.com/SUPERkelesss/superkelesss.github.io.git
repo_name: superkelesss.github.io

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  # æ ¼å¼åŒ–æ’ç‰ˆ
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
    

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # - https://3Dmol.org/build/3Dmol-min.js
  # - javascripts/vercel_statistics.js
  # - https://cdn.vercel.io/insights/script.js

extra_css:
#  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
  - stylesheets/toc_extra.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
