site_name: å‡¯æ¥½æ–¯Kelesssã®è–æ•™å›­åœ°
# å¯¼èˆªæ 
nav:
  - ğŸ é¦–é¡µ:
    - å…³äºæœ¬ç½‘ç«™: index.md
    - æœ€è¿‘æ›´æ–°: changelog.md
  - ğŸ§ªåŒ–å­¦:
    - åŒ–å­¦-é¦–é¡µ: "chem/index.md"
    - ç‰©ç†åŒ–å­¦:
      - ç‰©ç†åŒ–å­¦IIç¬”è®°: "chem/physical/Physical Chemistry II.md"
  - ğŸ”¢æ•°ç†:
    - æ•°ç†-é¦–é¡µ: "maphy/index.md"
    - æ•°å­¦:
      - æ•°ç†æ–¹æ³•: "maphy/math/Mathematic Method in Physics.md"
  - ğŸ–¥ï¸è®¡ç®—æœº:
    - è®¡ç®—æœº-é¦–é¡µ: "cs/index.md"
  - â˜•æ‚è´§é“º:
    - æ‚è´§é“º-é¦–é¡µ: "lqbz/index.md"
  - ğŸ“šèµ„æ–™:
    - èµ„æ–™-é¦–é¡µ: refs/index.md
  - ğŸ““æ—¥è®°:
    - æ—¥è®°-é¦–é¡µ: blog/index.md

# materialä¸»é¢˜
theme:
  name: material
  custom_dir: overrides

  text: JetBrains Mono, LXGW WenKai Screen GB Screen 
  code: JetBrains Mono, Consolas

  palette: 
    - scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  lang: zh
  favicon: libs/logos/favicon.png
  logo: libs/logos/favicon.png
  
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - search suggest
    - search highlight
    - search share
    - navigation.footer
    - navigation.indexes

plugins:
  - search:
      lang: 
        - zh
        - en
  - git-revision-date-localized
  - meta
  - blog: 
      blog_toc: true
      archive_date_format: MMMM yyyy
  - changelog

#é¡µè„š
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/SUPERkelesss
      - icon: bilibili-fill
        link: https://space.bilibili.com/334614292
      - icon: QQgroup
        link: https://qm.qq.com/q/YXattqg3Kg
      - icon: rednote
        link: https://www.xiaohongshu.com/user/profile/659dd609000000002001ca3b
      - icon: zhihu
        link: https://www.zhihu.com/people/ke-le-kelesss
copyright: Copyright Â© 2025 by <a href="https://github.com/SUPERkelesss" target="_blank">Kelesss</a> is licensed under CC BY-SA 4.0
#é¡µçœ‰
repo_url: https://github.com/SUPERkelesss/superkelesss.github.io.git
repo_name: superkelesss.github.io

extra_javascript:
  - javascripts/mathjax.js #æ”¹ä¸ºå¯¹Katexçš„æ”¯æŒ
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
#  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  # æ ¼å¼åŒ–æ’ç‰ˆ
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true